channels_string = """
http://nj.58.com//iphonesj/
http://nj.58.com//sanxing/
http://nj.58.com//nuojiya/
http://nj.58.com//htc/
http://nj.58.com//xiaomi/
http://nj.58.com//ailixin/
http://nj.58.com//zhongxingshouji/
http://nj.58.com//lgsj/
http://nj.58.com//kupaisj/
http://nj.58.com//huaweisj/
http://nj.58.com//lianxiang/
http://nj.58.com//motuoluola/
http://nj.58.com//heimei/
http://nj.58.com//jinlisj/
http://nj.58.com//meizu/
http://nj.58.com//shoujipeijian/
http://nj.58.com/http://pinpai.58.com/shouji/
http://nj.58.com//quanqiutong/
http://nj.58.com//shoujihao/?key=%E5%8A%A8%E6%84%9F%E5%9C%B0%E5%B8%A6
http://nj.58.com//shoujihao/?key=%E7%A5%9E%E5%B7%9E%E8%A1%8C
http://nj.58.com//ruyitong/
http://nj.58.com//cdma/
http://nj.58.com//tietong/
http://nj.58.com//chonzhika/
http://nj.58.com//shangwangshebei/
http://nj.58.com//shoujiyewu/
http://nj.58.com//xiaolingtong/
http://nj.58.com//wanliang/
http://nj.58.com//tabanmotuoche/
http://nj.58.com//qishiche/
http://nj.58.com//dapailiang/
http://nj.58.com//yueyemotuoche/
http://nj.58.com//yamaha/
http://nj.58.com//bentianmoto/
http://nj.58.com//jialing/
http://nj.58.com//lingmumoto/
http://nj.58.com//haojue/
http://nj.58.com//qingqi/
http://nj.58.com//zongshen/
http://nj.58.com//putongzixingche/
http://nj.58.com//zhediezixingche/
http://nj.58.com//minizixingche/
http://nj.58.com//gongluzixingche/
http://nj.58.com//changdizixingche/
http://nj.58.com//shandizixingche/
http://nj.58.com//jieante/
http://nj.58.com//meilida/
http://nj.58.com//yongjiu/
http://nj.58.com//fenghuangzxc/
http://nj.58.com//feige/
http://nj.58.com//jiema/
http://nj.58.com//diandongzixingche/
http://nj.58.com//diandongmotuoche/
http://nj.58.com//zhediediandongche/
http://nj.58.com//minidiandongche/
http://nj.58.com//zhudongche/
http://nj.58.com//jieanteddc/
http://nj.58.com//aima/
http://nj.58.com//xiaoniao/
http://nj.58.com//qingqiddc/
http://nj.58.com//lvyuanddc/
http://nj.58.com//xinri/
http://nj.58.com//jiaotasanlunche/
http://nj.58.com//diandongsanlunche/
http://nj.58.com//zhulisanlunche/
http://nj.58.com//zixingchepeijian/
http://nj.58.com//diandongchekongpeijian/
http://nj.58.com//diandongchedianchi/
http://nj.58.com//xiuchegongju/
http://nj.58.com//qixingzhuangbei/
http://nj.58.com//taishiji/
http://nj.58.com//fuwuqi/
http://nj.58.com//ibm/
http://nj.58.com//lenovo/
http://nj.58.com//apple/
http://nj.58.com//dell/
http://nj.58.com//asus/
http://nj.58.com//compaq/
http://nj.58.com//sony/
http://nj.58.com//samsung/
http://nj.58.com//pbdnipad/
http://nj.58.com//pbdnsanxing/
http://nj.58.com//pbdnlianxiang/
http://nj.58.com//pbdnaiguozhe/
http://nj.58.com//wangka/
http://nj.58.com//xianshiqi/
http://nj.58.com//cpu/
http://nj.58.com//xianka/
http://nj.58.com//zhuban/
http://nj.58.com//yingpan/
http://nj.58.com//ydyingpan/
http://nj.58.com//zhoubianshebei/pve_5620_398628/
http://nj.58.com//bujianduandianyuan/
http://nj.58.com//shubiao/
http://nj.58.com//shexiangtou/
http://nj.58.com//usb/
http://nj.58.com//smqita/pve_5623_398637/
http://nj.58.com//smqita/pve_5623_398636/
http://nj.58.com//smqita/
http://nj.58.com//danfanxiangji/
http://nj.58.com//kapianxiangji/
http://nj.58.com//weidanxiangji/
http://nj.58.com//jingtou/
http://nj.58.com//xiangjipeijian/
http://nj.58.com//qitaxiangji/
http://nj.58.com//ipod/
http://nj.58.com//mpsantouch/
http://nj.58.com//mpsannano/
http://nj.58.com//mpsan/
http://nj.58.com//mpsi/
http://nj.58.com//psp/
http://nj.58.com//yxjpsv/
http://nj.58.com//yxjnds/
http://nj.58.com//yxjxbox/
http://nj.58.com//yxjpssan/
http://nj.58.com//yxjpser/
http://nj.58.com//yxjwii/
http://nj.58.com//yingyinjiadian/
http://nj.58.com//shenghuojiadian/
http://nj.58.com//chuweijiadian/
http://nj.58.com//jiadianpeijian/
http://nj.58.com//yjcaidian/
http://nj.58.com//gqcaidian/
http://nj.58.com//dlzcaidian/
http://nj.58.com//biguakt/
http://nj.58.com//guishikt/
http://nj.58.com//zhongyangkt/
http://nj.58.com//quanzidongxiyiji/
http://nj.58.com//guntongxiyiji/
http://nj.58.com//shuanggangxiyiji/
http://nj.58.com//minixiyiji/
http://nj.58.com//shuangkaimenbx/
http://nj.58.com//duikaimenbx/
http://nj.58.com//minibx/
http://nj.58.com//lishibg/
http://nj.58.com//wohibg/
http://nj.58.com//zhanshibg/
http://nj.58.com//danrenchuang/
http://nj.58.com//shuanrenchuang/
http://nj.58.com//chuangcengchuang/
http://nj.58.com//zhediechuang/
http://nj.58.com//tongchuang/
http://nj.58.com//chuangdian/
http://nj.58.com//guizi/
http://nj.58.com//zhuolei/
http://nj.58.com//zuoju/
http://nj.58.com//jiajushafa/
http://nj.58.com//chaji/
http://nj.58.com//jujia/
http://nj.58.com//saomiaoyi/
http://nj.58.com//yitiji/
http://nj.58.com//chuanzhenji/
http://nj.58.com//touyingji/
http://nj.58.com//fuyinji/
http://nj.58.com//dayinji/
http://nj.58.com//tanfen/
http://nj.58.com//mohemoshui/
http://nj.58.com//wenjiangui/
http://nj.58.com//huiyizhuo/
http://nj.58.com//baoxiangui/
http://nj.58.com//bangongzhuoyi/
http://nj.58.com//bangongyi/
http://nj.58.com//bangongjiaju/pve_5733_398638/
http://nj.58.com//bangongjiaju/pve_5733_398639/
http://nj.58.com//huagong/
http://nj.58.com//fangzhi/
http://nj.58.com//fyinshua/
http://nj.58.com//gongcheng/
http://nj.58.com//zaozhi/
http://nj.58.com//kuangye/
http://nj.58.com//mugongshebei/
http://nj.58.com//diandongji/
http://nj.58.com//nongye/
http://nj.58.com//muyingzaojiao/
http://nj.58.com//ertongyongpin/
http://nj.58.com//zhiniaoku/
http://nj.58.com//yongpinlalaku/
http://nj.58.com//yongpinbeidai/
http://nj.58.com//yongpinxuebudai/
http://nj.58.com//yongpinyouxidai/
http://nj.58.com//yongpinjianshenjia/
http://nj.58.com//yongpinshuidai/
http://nj.58.com//naifen/
http://nj.58.com//weiyangfushi/
http://nj.58.com//weiyangyingyangpin/
http://nj.58.com//weiyangnaiping/
http://nj.58.com//weiyangnaizui/
http://nj.58.com//weiyangxinaiqi/
http://nj.58.com//weiyangnuannaiqi/
http://nj.58.com//yingerchuang/
http://nj.58.com//yingerche/
http://nj.58.com//tongchexuebu/
http://nj.58.com//tongcheyaoyi/
http://nj.58.com//tongzuoyi/
http://nj.58.com//tongcanyi/
http://nj.58.com//tongniuche/
http://nj.58.com//tongzixingche/
http://nj.58.com//tongsanlunche/
http://nj.58.com//yongpintaixin/
http://nj.58.com//fangfusefu/
http://nj.58.com//mmfuzhuang/
http://nj.58.com//yongpinshoufu/
http://nj.58.com//yongpinyunfuzhen/
http://nj.58.com//fushipeijian/
http://nj.58.com//fuzhuangshoushi/
http://nj.58.com//fuzhuangshoubiao/
http://nj.58.com//fuzhuangtxue/
http://nj.58.com//fuzhuangchenshan/
http://nj.58.com//fuzhuangwaitao/
http://nj.58.com//fuzhuangkuzi/
http://nj.58.com//qunzifs/
http://nj.58.com//fuzhuangxizhuang/
http://nj.58.com//tongzhuang/
http://nj.58.com//xiuxianxie/
http://nj.58.com//yundongxie/
http://nj.58.com//fanbuxie/
http://nj.58.com//gaogenxie/
http://nj.58.com//xiebanxi/
http://nj.58.com//pixie/
http://nj.58.com//xiangbaodanjian/
http://nj.58.com//xiangbaoshuangjian/
http://nj.58.com//xiangbaoshubao/
http://nj.58.com//xiangbaoqianbao/
http://nj.58.com//xiangbaolagan/
http://nj.58.com//xiangbaodiannao/
http://nj.58.com//meirongyongpin/
http://nj.58.com//hufu/
http://nj.58.com//meirongmeiti/
http://nj.58.com//caizhuang/
http://nj.58.com//baojianshipin/
http://nj.58.com//meifa/
http://nj.58.com//xiangshuimr/
http://nj.58.com//gudongguwan/
http://nj.58.com//mingxingwupin/
http://nj.58.com//shufa/
http://nj.58.com//shanshuihua/
http://nj.58.com//renwuhua/
http://nj.58.com//huaniaohua/
http://nj.58.com//zhuangshihua/
http://nj.58.com//guijinshu/
http://nj.58.com//zhubaoshshi/
http://nj.58.com//fangjinshshi/
http://nj.58.com//zhubaoshipin/pve_5731_398646/
http://nj.58.com//zhubaoshipin/pve_5731_398647/
http://nj.58.com//youpiaoyoupin/
http://nj.58.com//fanggujiaju/
http://nj.58.com//aoyunjinianbi/
http://nj.58.com//sbjinianpin/
http://nj.58.com//cddvd/
http://nj.58.com//yingpandianshiju/
http://nj.58.com//ruanjiants/
http://nj.58.com//jishulei/
http://nj.58.com//gongjushu/
http://nj.58.com//kaoshi/
http://nj.58.com//shenghuolei/
http://nj.58.com//xiaoshuo/
http://nj.58.com//youyongwt/
http://nj.58.com//yujiawt/
http://nj.58.com//diaoyuyongju/
http://nj.58.com//qipai/
http://nj.58.com//yundongfushi/pve_5728_398644/
http://nj.58.com//yundongfushi/pve_5728_398648/
http://nj.58.com//tabuji/
http://nj.58.com//peobuji/
http://nj.58.com//anmoyi/
http://nj.58.com//liubinghuaban/
http://nj.58.com//jianshenche/
http://nj.58.com//xueshwenju/
http://nj.58.com//jiaoxueyj/
http://nj.58.com//taiqiuzhuo/
http://nj.58.com//wangqiuyongpin/
http://nj.58.com//zuqiuwt/
http://nj.58.com//pingpangqiuwt/
http://nj.58.com//yumaoqiuwt/
http://nj.58.com//lanqiutw/
http://nj.58.com//jita/
http://nj.58.com//gangqin/
http://nj.58.com//dianziqin/
http://nj.58.com//shoufengqing/
http://nj.58.com//erhuwt/
http://nj.58.com//yintundaomo/
http://nj.58.com//xingwanou/
http://nj.58.com//jiandanbianxie/
http://nj.58.com//nanyongchuandai/
http://nj.58.com//fangzhenrufang/
http://nj.58.com//zhendongbang/
http://nj.58.com//yindiciji/
http://nj.58.com//gdianhouting/
http://nj.58.com//tiaodan/
http://nj.58.com//fengrutiaodou/
http://nj.58.com//jiqingyongju/
http://nj.58.com//qingqutiaosao/
http://nj.58.com//lingleiwanju/
http://nj.58.com//yanshitaohuan/
http://nj.58.com//tiaoqingxiangshui/
http://nj.58.com//zhifuyouhuo/
http://nj.58.com//dingziku/
http://nj.58.com//siwameitui/
http://nj.58.com//nanshineiyi/
http://nj.58.com//runhuaji/
http://nj.58.com//aqyp/
http://nj.58.com//anquantao/
http://nj.58.com//qitachengren/
http://nj.58.com//xiaoyuan/pve_5536_1/
http://nj.58.com//xiaoyuan/pve_5536_2/
http://nj.58.com//xiaoyuan/pve_5536_3/
http://nj.58.com//xiaoyuan/pve_5536_4/
http://nj.58.com//xiaoyuan/pve_5536_5/
http://nj.58.com//esqgjiaju/
http://nj.58.com//esqgfuzhuang/
http://nj.58.com//esqgtushu/
http://nj.58.com//ershouqiugou/
http://nj.58.com//wangyou/
http://nj.58.com//huanwu/
http://nj.58.com//lipin/
http://nj.58.com//wuyuanwupin/
http://nj.58.com//fuwujy/
http://nj.58.com//canjirenyongpin/
http://nj.58.com//weixing/
http://nj.58.com//qitatiaozao/
"""